### PR TITLE
Normalized movement which fixes incorrect diagonal movement speed

### PR DESCRIPTION
**Pull request by LorisSecuro**
Issue #11 

I believe that issue #2 does not completely solve the problem of diagonal movement speed.

It limits the maximum speed, but does not limit the acceleration speed.
For example it adds 25 to x and 25 to y when going diagonally instead of 17.677 and 17.677, which still will make diagonal movement slightly faster than it should be.

This should fix both the acceleration speed and the maximum speed.

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
So, I am trying to understand what you did. To me it seems that this will not work correctly with a Vector that contains negative values. Correct me if I am wrong, but the previous solution took that into consideration, as the `clamp` function was actually given bounds instead of just a maximum value `like Vector2D#clamped`.

**Comment by LorisSecuro** [comment]
`Vector2D#clamped` does fix also the negative values, add a `print(mov_accel)` and you'll see that it is working correctly.

From the documentation: 

> Returns the vector with a maximum length.

It is referring to the length of the vector, it doesn't matter if negative or positive.

**Comment by Bios-Marcel** [comment]
Okay, you are right. Anyhow, we just did bigger changes to the file system structure. would you mind checking out our develop again and just redoing that change?

I assume just closing this PR and making a new one is fine ^^

**Comment by LorisSecuro** [comment]
I think the PR is now OK.

**Pull request merged**
